### ISSUE TITLE
Daily Checklist

### ISSUE THREAD

**Issue by daverex956** [daverex956/Personal#5]
Optimize all Tasks --- Details

### Tuesday Checklist
- [ ] Create Github Assignments

>- [ ]  Roundtable Video Edit
>- [ ] Fireside Live Stream
>- [ ] Antelope (Monthly)
>- [ ] EOS HOT SAUCE

- [ ] GEMS Meeting
- [ ] Review and Edit Video Production
- [ ] Exec Meeting

### Wednesday Checklist
- [ ] Streaming Fireside

### Thursday Checklist
👷‍♂️ [Workflow](https://www.canva.com/design/DAFqZzk58aA/3p4zLBuwd0ond_hm02MGEA/edit)

- [ ] Roundtable
- [ ] Fireside
> - [ ] Fireside Timestamps
> > - [ ] Update Youtube Description
> - [ ] Master Fireside Audio
> - [ ] Upload to Anchor.FM

> - [ ] Pinax Executive Call 2PM

### Friday Checklist
- [ ] Research and Development
